/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarPagination: typeof import('@varlet/ui')['_PaginationComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
  }
}
